"""add refresh tokens

Revision ID: 30ffee3fc35c
Revises: 322dcbd9dc01
Create Date: 2026-07-31 13:17:59.590538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ffee3fc35c'
down_revision: Union[str, Sequence[str], None] = '322dcbd9dc01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['enterprise_ai.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise_ai'
    )
    op.create_index(op.f('ix_enterprise_ai_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True, schema='enterprise_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enterprise_ai_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='enterprise_ai')
    op.drop_table('refresh_tokens', schema='enterprise_ai')
    # ### end Alembic commands ###
