"""update document chunks

Revision ID: bb24eb3bb530
Revises: fe0b4e2c8164
Create Date: 2026-08-05 14:26:12.226088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb24eb3bb530'
down_revision: Union[str, Sequence[str], None] = 'fe0b4e2c8164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True), schema='enterprise_ai')
    op.add_column('document_chunks', sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='enterprise_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'chunk_metadata', schema='enterprise_ai')
    op.drop_column('document_chunks', 'page_number', schema='enterprise_ai')
    # ### end Alembic commands ###
