"""create document chunks table

Revision ID: fe0b4e2c8164
Revises: 5a2195b08789
Create Date: 2026-08-05 12:48:45.268965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0b4e2c8164'
down_revision: Union[str, Sequence[str], None] = '5a2195b08789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['enterprise_ai.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise_ai'
    )
    op.create_index(op.f('ix_enterprise_ai_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False, schema='enterprise_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enterprise_ai_document_chunks_document_id'), table_name='document_chunks', schema='enterprise_ai')
    op.drop_table('document_chunks', schema='enterprise_ai')
    # ### end Alembic commands ###
